### ISSUE TITLE
Setup instructions?

### ISSUE THREAD

**Issue by alsbury** [michaelusner/pool#1]
Hi,
I have a Pentair variable speed pump that I bought last year as well as a booster pump for my pool sweeper. Also have the ScreenLogic garbage that they sell (shameful). Can you provide some details on how to use this code.  I'm a coder, but don't know much about Python or how you are connecting to the pump.

**Comment by michaelusner** [comment]
Hi, I've been planning on writing up a tutorial with photos etc.
Since I decided to rewrite the code in node.js, I'll upload when it's complete.  The basics are there, but since I'm a newbie to node.js, I don't want to upload something shameful.

The first thing you'll need is an RS485 to RS232 converter.  I got one from Amazon.  The next thing is to connect 2 wires to the Pentair controller, open up a serial terminal, and see if you get a stream of bytes.  After that, it's a matter of running the code.

I'll provide some updated node.js code and instructions and will notify you when it's ready.

Thanks for the feedback.

**Comment by alsbury** [comment]
Hi,
I was actually planning to do the same basic thing. Gonna buy a Raspberry Pi 2 and try and either install MEAN (Mongo, Express, Angular, Node) stack or Meteor JS. Both platforms I am a rookie, but seemed like an ideal fit.

Have you considered creating a Bitbucket account and keeping the repo private for now?  Later you could migrate it to Github (or never). I have snooped the traffic between the Screenlogic app and the Screenlogic serial bridge, so I am pretty sure I am really close to being able to plug in a serial cable.

If you were willing to share your code, I promise I won’t be critical :) I work with programmers of all skill levels all the time and I know how it is to be new to a platform. And if you don’t want to do that, would you mind sharing the original code?

Any help would be appreciated.

Thanks,
David

**Comment by michaelusner** [comment]
OK - consider my arm twisted :)
https://github.com/michaelusner/Home-Device-Controller

I've made the repo public and added some documentation.  Let me know how it goes and I can grow/improve from here.

Thanks,
Mike

**Comment by alsbury** [comment]
Thanks, really appreciate it :)
